# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2019 Intel Corporation

run:
  tests: true
  skip-files:
    - "^\\+S\\.pb\\.go"

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - structcheck
    - varcheck
    - ineffassign
    - typecheck
    - deadcode
    - golint
    - gosec
    - interfacer
    - unconvert
    - goconst
    - gocyclo
    - gofmt
    - maligned
    - misspell
    - lll
  enable-all: false

linters-settings:
  gocyclo:
    min-complexity: 12
  govet:
    check-shadowing: true
  misspell:
    locale: US
  lll:
    line-length: 120
    tab-width: 4

issues:
  exclude-rules:
    - text: "string `*`"
      linters:
        - goconst

# Disable the default exclude patterns
exclude-use-default: false
