# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2020 Intel Corporation

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: csr-signer
  namespace: smartedge-system

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: csr-signer
rules:
  - apiGroups: [certificates.k8s.io]
    resources: [certificatesigningrequests]
    verbs: [get, list, watch, create]
  - apiGroups: [certificates.k8s.io]
    resources: [certificatesigningrequests/status]
    verbs: [update]
  - apiGroups: [certificates.k8s.io]
    resources: [signers]
    resourceNames: [smartedge.org/certsigner]
    verbs: [sign]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csr-signer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: csr-signer
subjects:
  - kind: ServiceAccount
    name: csr-signer
    namespace: smartedge-system

---
  apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRole
  metadata:
    name: csr-requester
  rules:
    - apiGroups: [certificates.k8s.io]
      resources: [certificatesigningrequests]
      verbs: [get, list, watch, create, delete]
